name: Pull Request Assignment

on:
    pull_request:
        types: [opened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign pullrequest'
              uses: pozil/auto-assign-issue@v1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  assignees: ${{github.actor}} 
            - name: 'Sets label 09 Pending Peer Review'
              uses: actions-ecosystem/action-add-labels@v1
              with:
                labels: 09 Pending Peer Review
